#!/bin/bash

function display_help {
    echo "Wrapper around github.com/kr/goven to automatically import and update third
party dependencies by the use of go list tool.
    
Usage:

    ./`basename $0` <args> [options]


Commands:

    list        list dependencies
    up          update dependencies

Options:

    -a|--all    update all dependencies
    -h|--help   show this help
    "
    exit
}

function error {
    echo "ERR: $@" 1>&2
}

function fail {
    error "program terminated"
    exit 1
}

function find-deps {
    if [ ! $# -eq 1 ] ; then
        return 1
    fi

    local pkg=$1
    local deps=`go list -f '{{join .Deps "\n"}}' ${pkg} |
        xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}'`
    echo "${deps}"
}

function update {
    local update=false
    [[ $1 == --all* || $1 == -a* ]] && update=true

    local cwd=`pwd`

    for pkg in $(find-deps "./..."); do
        local dir="`go list -f '{{.Dir}}' ${pkg}`" || return 1

        # don't consider sub-packages
        if [[ ${dir} == ${cwd}* ]]; then
            if [[ ${dir} != ${cwd}/third_party* ]]; then
                continue
            fi

            if ! ${update} ; then
                continue
            fi

            # unless sub-package is a third_party pkg, then grab the real
            # package import path
            pkg="${pkg#*third_party/}" || return 1
        fi

        if [[ ${pkg} == "." ]]; then
            error "unexpected pkg name"
            return 1
        fi

        goven -copy -rewrite -prefix="third_party" ${pkg} || return 1

        # rewrite import of third_party which depend on each other
        for ddep in $(find-deps "${pkg}"); do
            goven -copy=false -prefix="third_party" ${ddep} || return 1
        done
    done

    go fmt ./...
}

if [ -z "${GOPATH}" ]; then
    error "GOPATH must be set"
    exit 1
fi

# parse options
while true; do
    case "$1" in
        list)
            find-deps "./..."
            exit
            ;;
        up)
            shift
            update $@ || fail
            exit
            ;;
        -h|--help)
            display_help
            ;;
        *)
            display_help
            ;;
    esac
    shift;
done
